#!/bin/sh

#DATADIR="/media/jilanxin/DATA2/fetal_brain/FSL_test_example/2013-T1"
#TMP="/media/jilanxin/DATA2/fetal_brain/FetalAtlas/weekly-T2/wk32"
DATADIR=$1

echo $DATADIR

cd $DATADIR
cp /media/jilanxin/DATA2/fetal_brain/FSL_test_example/realign2.fsf rfMRI.fsf 

fmriNumVol=`fslval merged_data_std-avg.nii.gz dim4`

echo "set feat_files(1)       \""$DATADIR"/merged_data_std-avg.nii.gz\"" >> rfMRI.fsf 
echo "set fmri(npts) $fmriNumVol"  >> rfMRI.fsf

feat rfMRI.fsf


#/usr/local/fsl/bin/mcflirt -in prefiltered_func_data -out prefiltered_func_data_mcf -mats -plots -reffile example_func -rmsrel -rmsabs -spline_final

#/bin/mkdir -p mc ; /bin/mv -f prefiltered_func_data_mcf.mat prefiltered_func_data_mcf.par prefiltered_func_data_mcf_abs.rms prefiltered_func_data_mcf_abs_mean.rms prefiltered_func_data_mcf_rel.rms prefiltered_func_data_mcf_rel_mean.rms mc

#/usr/local/fsl/bin/fsl_tsplot -i prefiltered_func_data_mcf.par -t 'MCFLIRT estimated rotations (radians)' -u 1 --start=1 --finish=3 -a x,y,z -w 640 -h 144 -o rot.png 

#/usr/local/fsl/bin/fsl_tsplot -i prefiltered_func_data_mcf.par -t 'MCFLIRT estimated translations (mm)' -u 1 --start=4 --finish=6 -a x,y,z -w 640 -h 144 -o trans.png 

#/usr/local/fsl/bin/fsl_tsplot -i prefiltered_func_data_mcf_abs.rms,prefiltered_func_data_mcf_rel.rms -t 'MCFLIRT estimated mean displacement (mm)' -u 1 -w 640 -h 144 -a absolute,relative -o disp.png 

