#!/usr/bin/env bash
#
# Script name: tnice_prepare_structure
#
# Description: Script to generate the FEAT configuration file for resting fMRI.
#
# Authors: Lanxin Ji	
#
# Copyright 2020 NCRC, Tiantan Hospital

# export BB_BIN_DIR="/Users/hanalytics/Documents/UK_biobank_pipeline_v_1-master"
# sh init_vars

cd ./T1

#GDC
$BB_BIN_DIR/bb_pipeline_tools/bb_GDC --workingdir=T1_GDC/ --in=T1_orig.nii.gz --out=T1_orig_ud.nii.gz --owarp=T1_orig_ud_warp.nii.gz

#crop neck
head_top=`${FSLDIR}/bin/robustfov -i T1_orig_ud | grep -v Final | head -n 1 | awk '{print $5}'`
${FSLDIR}/bin/fslmaths T1_orig_ud -roi 0 -1 0 -1 $head_top 170 0 1 T1_tmp

#remove skull
${FSLDIR}/bin/bet T1_tmp T1_tmp_brain -R

#create linear warp from T1_tmp_brain to standard space & reduce FOV of T1_orig_ud as T1
${FSLDIR}/bin/standard_space_roi T1_tmp_brain T1_tmp2 -maskNONE -ssref $FSLDIR/data/standard/MNI152_T1_1mm_brain -altinput T1_orig_ud -d
mv T1_tmp2.nii.gz T1.nii.gz

#create linear warp from T1 to MNI
${FSLDIR}/bin/flirt -in T1 -ref T1_orig_ud -omat T1_to_T1_orig_ud.mat -schedule $FSLDIR/etc/flirtsch/xyztrans.sch
${FSLDIR}/bin/convert_xfm -omat T1_orig_ud_to_T1.mat -inverse T1_to_T1_orig_ud.mat
${FSLDIR}/bin/convert_xfm -omat T1_to_MNI_linear.mat -concat T1_tmp2_tmp_to_std.mat T1_to_T1_orig_ud.mat

#Non-linear reg from T1 to MNI
${FSLDIR}/bin/fnirt --in=T1 --ref=$FSLDIR/data/standard/MNI152_T1_1mm --aff=T1_to_MNI_linear.mat --config=$BB_BIN_DIR/bb_data/bb_fnirt.cnf --refmask=$BB_BIN_DIR/templates/MNI152_T1_1mm_brain_mask_dil_GD7 --logout=../logs/bb_T1_to_MNI_fnirt.log --cout=T1_to_MNI_warp_coef --fout=T1_to_MNI_warp --jout=T1_to_MNI_warp_jac --iout=T1_tmp4.nii.gz --interp=spline

#Apply all above warp to T1_orig
${FSLDIR}/bin/convertwarp --ref=$FSLDIR/data/standard/MNI152_T1_1mm --warp1=T1_orig_ud_warp --midmat=T1_orig_ud_to_T1.mat --warp2=T1_to_MNI_warp --out=T1_orig_to_MNI_warp
${FSLDIR}/bin/applywarp --rel -i T1_orig -r $FSLDIR/data/standard/MNI152_T1_1mm -w T1_orig_to_MNI_warp -o T1_brain_to_MNI --interp=spline

#Create and apply brain mask in both standard space and individual space
${FSLDIR}/bin/invwarp --ref=T1 -w T1_to_MNI_warp_coef -o T1_to_MNI_warp_coef_inv
${FSLDIR}/bin/applywarp --rel --interp=trilinear --in=$BB_BIN_DIR/templates/MNI152_T1_1mm_brain_mask --ref=T1 -w T1_to_MNI_warp_coef_inv -o T1_brain_mask
${FSLDIR}/bin/fslmaths T1 -mul T1_brain_mask T1_brain
${FSLDIR}/bin/fslmaths T1_brain_to_MNI -mul $BB_BIN_DIR/templates/MNI152_T1_1mm_brain_mask T1_brain_to_MNI

#Defacing T1
${FSLDIR}/bin/convert_xfm -omat grot.mat -concat T1_to_MNI_linear.mat T1_orig_ud_to_T1.mat
${FSLDIR}/bin/convert_xfm -omat grot.mat -concat $BB_BIN_DIR/templates/MNI_to_MNI_BigFoV_facemask.mat grot.mat
${FSLDIR}/bin/convert_xfm -omat grot.mat -inverse grot.mat
${FSLDIR}/bin/flirt -in $BB_BIN_DIR/templates/MNI152_T1_1mm_BigFoV_facemask -ref T1_orig -out grot -applyxfm -init grot.mat
${FSLDIR}/bin/fslmaths grot -binv -mul T1_orig T1_orig_defaced

cp T1.nii.gz T1_not_defaced_tmp.nii.gz  
${FSLDIR}/bin/convert_xfm -omat grot.mat -concat $BB_BIN_DIR/templates/MNI_to_MNI_BigFoV_facemask.mat T1_to_MNI_linear.mat
${FSLDIR}/bin/convert_xfm -omat grot.mat -inverse grot.mat
${FSLDIR}/bin/flirt -in $BB_BIN_DIR/templates/MNI152_T1_1mm_BigFoV_facemask -ref T1 -out grot -applyxfm -init grot.mat
${FSLDIR}/bin/fslmaths grot -binv -mul T1 T1

#Generation of QC value: Number of voxels in which the defacing mask goes into the brain mask
${FSLDIR}/bin/fslmaths T1_brain_mask -thr 0.5 -bin grot_brain_mask 
${FSLDIR}/bin/fslmaths grot -thr 0.5 -bin -add grot_brain_mask -thr 2 grot_QC
${FSLDIR}/bin/fslstats grot_QC.nii.gz -V | awk '{print $ 1}' > T1_QC_face_mask_inside_brain_mask.txt

rm grot*


#Clean and reorganize
rm *tmp*
mkdir transforms
mv *MNI* transforms
mv *warp*.* transforms
mv *_to_* transforms
mv transforms/T1_brain_to_MNI.nii.gz .

cd ..


